@ WARNING:  This file was automatically generated by lorraine.
@           Do not make changes to this file!

        .section .rodata
        .align

        .include "game.inc"

        .global level_gym
level_gym:
        .hword 0<<6 | 2<<4
        .byte 0, 3
        .incbin "levels/gym/alpha_fg.pal"
        .incbin "levels/gym/beta_fg.pal"
        @ tileset pointers
        .word medical_alpha_bg_tiles
        .word gym_alpha_fg_tiles
        .word medical_beta_bg_tiles
        .word gym_beta_fg_tiles
        @ layer pointers
        .word gym_alpha_fg_mrle
        .word medical_alpha_bg_mrle
        .word 0
        .word 0
        .word gym_beta_fg_mrle
        .word medical_beta_bg_mrle
        .word 0
        .word 0
        @ line bank
        .incbin "levels/gym/gym.lnd"
        .align
        @ alpha segtree
        .word 1f-0f
0:      .incbin "levels/gym/alpha_sp.tree"
        .align
1:
        @ beta segtree
        .word 1f-0f
0:      .incbin "levels/gym/beta_sp.tree"
        .align
1:
        @ actors
        .hword ARCH_GREEN_TROOPER
        .byte 0, 0b00010111
        .hword 100, 100
        .byte 0
        .align
        .hword ARCH_GREEN_TROOPER
        .byte 0, 0b00010111
        .hword 200, 200
        .byte 0
        .align
        .hword ARCH_PLATFORM
        .byte 0, 0b00010111
        .hword 1160, 1080
        .byte 8, 0, 0, 0, 0, 0, 0, 0, 0
        .align
        @ local tilesets
gym_alpha_fg_tiles:
        .hword (2<<14) | 183
        .hword 0
        .incbin "levels/gym/alpha_fg.tiles"
        .align
gym_beta_fg_tiles:
        .hword (2<<14) | 72
        .hword 0
        .incbin "levels/gym/beta_fg.tiles"
        .align
        @ local maps
gym_alpha_fg_mrle:
        .hword 252, 160
        .byte (2 << 6) | (2 << 4) | (0)
        .byte 128
        .byte 0, 0
        .incbin "levels/gym/alpha_fg.mrle"
gym_beta_fg_mrle:
        .hword 252, 160
        .byte (2 << 6) | (2 << 4) | (2)
        .byte 128
        .byte 0, 0
        .incbin "levels/gym/beta_fg.mrle"

@ EOF gym.s -- DO NOT MODIFY DIRECTLY
